const cardsData = {
    neutral: {
        units: [
            {
                id: 'neutral_unit_1',
                name: 'Геральт',
				namefull: 'Геральт из Ривии',
                strength: 10,
                type: 'unit',
                faction: 'neutral',
                image: 'geralt.mp4',
                description: 'Белый Волк',
				descriptionfull: 'Ведьмак школы Волка. Профессиональный охотник на чудовищ и один из лучших фехтовальщиков Севера, герой сказаний и легенд и невольный телохранитель королей. Стараясь не встревать ни в какие передряги и во всём придерживаться нейтралитета, Геральт, однако, часто оказывается меж двух огней и вынужден выбирать сторону в назревающих столкновениях.',
				ability: 'geralt',
                position: 'any-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
            {
                id: 'neutral_unit_2',
                name: 'Весемир',
				namefull: 'Весемир',
                strength: 7,
                type: 'unit',
                faction: 'neutral',
                image: 'vesemir.mp4',
                description: 'Наставник школы Волка',
				descriptionfull: 'Глава Школы Волка, одной из пяти ведьмачьих школ, и самый старший ведьмак на континенте. Несмотря на седину и преклонный возраст, он продолжает управлять школой и охотиться на чудовищ, своим примером показывая, что некоторые знания приходят только с опытом.',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'silver',
                tags: ['witcher'],
                border: 'deck/bord_silver.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_unit_3',
                name: 'Цири',
				namefull: 'Цирилла Фиона Элен Рианнон',
                strength: 9,
                type: 'unit',
                faction: 'neutral',
                image: 'ciri.mp4',
                description: 'Дитя Старшей Крови',
				descriptionfull: 'Наследница престола Нильфгаардской империи, лихая ведьмачка, обладающая невероятными магическими способностями, а также Дитя-Неожиданность и фактически приёмная дочь Геральта из Ривии.',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
            {
                id: 'neutral_unit_4',
                name: 'Йеннифэр',
				namefull: 'Йеннифэр из Венгерберга',
                strength: 6,
                type: 'unit',
                faction: 'neutral',
                image: 'yennifer.mp4',
                description: 'Женщина с запахом сирени и крыжовника',
				descriptionfull: 'Талантливая и могущественная чародейка. Входила в состав последнего Совета Чародеев, позднее — в Ложу Чародеек. Правителей, при которых она состояла советницей, Йеннифэр использовала для достижения собственных целей. Что же до любовников… ими она всегда вертела как хотела.',
				ability: '---',
                position: 'siege-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['mage'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
            {
                id: 'neutral_unit_5',
                name: 'Трисс',
				namefull: 'Трисс Меригольд',
                strength: 8,
                type: 'unit',
                faction: 'neutral',
                image: 'triss.mp4',
                description: 'Четырнадцатая с Холма',
				descriptionfull: 'Чародейка, целительница и алхимик, одна из самых молодых, но вместе с тем самых талантливых магов Севера, а также советница короля Фольтеста, подруга Йеннифэр, Цири и ведьмаков из Каэр Морхена, состоявшая в близких отношениях с Геральтом. Участвовала в битве под Содденом, в ходе которой потеряла свои волосы и покалечила тело, притом была ошибочно признана погибшей, а после спасения длительное время проходила реабилитацию и лечение и впоследствии получила прозвище «Четырнадцатая с Холма».',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['mage'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
			{
                id: 'neutral_unit_6',
                name: 'Гезрас',
				namefull: 'Гезрас из Лейды',
                strength: 8,
                type: 'unit',
                faction: 'neutral',
                image: 'gezras.mp4',
                description: 'Предводитель школы Кота',
				descriptionfull: 'Гезрас был рождён полуэльфом — по мнению большинства, негодным выродком. Когда его продали чародеям из замка Стигга, он был совсем ребёнком. Его подвергли мутациям, которые придумали недавно в расчёте на то, чтобы сильнее подавлять эмоции новоиспечённых ведьмаков. Эксперимент закончился провалом. По иронии судьбы мутации не сдержали эмоции, а усилили их проявление. Из-за них Гезрас и его новые собратья отличались большей неуравновешенностью.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
			{
                id: 'neutral_unit_7',
                name: 'Арнагад',
				namefull: 'Арнагад',
                strength: 8,
                type: 'unit',
                faction: 'neutral',
                image: 'arnagad.mp4',
                description: 'Основатель школы Медведя',
				descriptionfull: 'Один из первых ведьмаков и основатель Школы Медведя. Арнагад же был убеждён, что ведьмачье ремесло — лишь работа, не больше и не меньше. Ведьмак должен искать заказы, убивать чудовищ и брать за это плату. Всё остальное, утверждал он, лишь раздувает чувство собственной важности.',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
			{
                id: 'neutral_unit_8',
                name: 'Ивар',
				namefull: 'Ивар Злобоглаз',
                strength: 8,
                type: 'unit',
                faction: 'neutral',
                image: 'ivar.mp4',
                description: 'Основатель школы Змеи',
				descriptionfull: 'Мастер-ведьмак прошлого, основатель и многолетний лидер Школы Змеи, боровшийся с Дикой Охотой. Вопреки слухам, Школа Змеи была основана с великой целью, а вовсе не для того, чтобы предлагать богачам всевозможные услуги по избавлению от врагов. Мастер-ведьмак Ивар Злобоглаз понимал, что не достигнет в одиночку своей истинной цели — отыскать и одолеть Дикую Охоту.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
			{
                id: 'neutral_unit_9',
                name: 'Эрланд',
				namefull: 'Эрланд из Ларвика',
                strength: 8,
                type: 'unit',
                faction: 'neutral',
                image: 'erland.mp4',
                description: 'Основатель школы Грифона',
				descriptionfull: 'Один из первых созданных ведьмаков, первый гроссмейстер Школы Грифона, а также её основатель. Имея огромное уважение и даже получал приглашения к королевским дворам с просьбами о помощи или совете, он не оставлял свою деятельность и продолжал лично охотиться на чудовищ, считая это своим долгом и Предназначением.',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
			{
                id: 'neutral_unit_10',
                name: 'Лео Бонарт',
				namefull: 'Лео Бонарт',
                strength: 8,
                type: 'unit',
                faction: 'neutral',
                image: 'bonart.mp4',
                description: 'Охотник на ведьмаков',
				descriptionfull: 'Профессиональный наёмный убийца и охотник за головами. Из отличительных признаков — ведьмачьи медальоны Школы Кота, Школы Грифона и Школы Волка, которые он носил в качестве трофеев.',
				ability: '---',
                position: 'siege-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
        ],
        specials: [
            {
                id: 'neutral_special_1',
                name: 'Проливной дождь',
                type: 'special',
                faction: 'neutral',
                image: 'rain.mp4',
                description: 'Погода',
				descriptionfull: 'Осадная башня увязла в грязи!',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_special_2',
                name: 'Трескучий мороз',
                type: 'special',
                faction: 'neutral',
                image: 'cold.mp4',
                description: 'Погода',
				descriptionfull: 'У меня пальцы так заледенели, едва меч держу... А ведь мечом еще и махать надо...',
				ability: 'impenetrable_fog',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_special_3',
                name: 'Густой туман',
                type: 'special',
                faction: 'neutral',
                image: 'fog.mp4',
                description: 'Погода',
				descriptionfull: 'Вот туман-то... Хоть глаз выколи.',
				ability: 'impenetrable_fog',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_special_4',
                name: 'Чистое небо',
                type: 'special',
                faction: 'neutral',
                image: 'sun.mp4',
                description: 'Погода',
				descriptionfull: 'Хороший день, чтобы умереть.',
				ability: 'clear_weather',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
		],
        tactics: [],
        artifacts: [],
    },

    monsters: {
        units: [
            {
                id: 'monsters_unit_1',
				name: 'Эредин',
				namefull: 'Эредин Бреакк Глас',
				strength: 10,
				type: 'unit',
				faction: 'monsters',
				image: 'eredin.mp4',
				description: 'Король Дикой Охоты',
				descriptionfull: 'Король Дикой Охоты, призрачных эльфийских всадников, которых считают предвестниками злого рока. Дикая Охота странствует между мирами в поисках средства, что спасло бы их родные земли от чудовищного катаклизма, Белого Хлада. Эредин — безжалостный правитель, он не останавливается ни перед чем на пути к своей цели. Если он поклялся найти Цири — значит, рано или поздно это произойдёт.',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
				rarity: 'gold',
				tags: ['leader', 'wild_hunt'],
				border: 'deck/bord_gold.png',
				banner: 'faction/monsters/banner_gold.png'
            },
            {
                id: 'monsters_unit_2',
                name: 'Имлерих',
				namefull: 'Имлерих',
                strength: 9,
                type: 'unit',
                faction: 'monsters',
                image: 'imlerih.mp4',
                description: 'Генерал Дикой Охоты',
				descriptionfull: 'Полководец Дикой Охоты и правая рука Эредина. Могучий и опытный воин огромного роста, на голову возвышающийся над всеми обитателями мира Континента и превосходящий по размерам даже своих собратьев.',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
				rarity: 'gold',
                tags: ['wild_hunt'],
                border: 'deck/bord_gold.png',
                banner: 'faction/monsters/banner_gold.png'
            },
            {
                id: 'monsters_unit_3',
                name: 'Карантир',
				namefull: 'Карантир Ар-Фейниэль',
                strength: 6,
                type: 'unit',
                faction: 'monsters',
                image: 'karantir.mp4',
                description: 'Навигатор Дикой Охоты',
				descriptionfull: 'Могущественный чародей-навигатор и лейтенант Дикой Охоты. Кроме того, благодаря уникальной наследственности навигатор обладал способностями к древней магии, открывающей ему путь в ледяную пустоту, отделяющую мир от другого, а оттуда — в любой из известных ему миров.',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'gold',
                tags: ['wild_hunt'],
                border: 'deck/bord_gold.png',
                banner: 'faction/monsters/banner_gold.png'
            },
            {
                id: 'monsters_unit_4',
                name: 'Нитраль',
				namefull: 'Нитраль',
                strength: 6,
                type: 'unit',
                faction: 'monsters',
                image: 'nitral.mp4',
                description: 'Всадник Дикой Охоты',
				descriptionfull: 'Высокопоставленный эльф из народа Aen Elle, всадник Дикой Охоты. Обладает некими магическими способностями, поскольку может открывать порталы, окружать себя защитной сферой и телепортироваться. ',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'gold',
                tags: ['wild_hunt'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
			{
                id: 'monsters_unit_5',
                name: 'Хим',
				namefull: 'Хим',
                strength: 3,
                type: 'unit',
                faction: 'monsters',
                image: 'hym.mp4',
                description: 'Дух',
				descriptionfull: 'Дух, питающийся страхом и страданиями преступника. Хим привязывается к человеку, совершившему какой-то низкий поступок или преступление, однако, если человек не сожалеет и не переживает о своём поступке, чудовище не сможет овладеть им. Завладев жертвой, хим питается её негативными переживаниями и эмоциями, но, неспособный насытиться, вызывает эти чувства вновь и вновь, при этом жертва не может даже увидеть монстра.',
				ability: 'eredin_ability',
                position: 'ranged-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'bronze',
                tags: ['monster'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
			{
                id: 'monsters_unit_6',
                name: 'Феникс',
				namefull: 'Феникс',
                strength: 5,
                type: 'unit',
                faction: 'monsters',
                image: 'phoenix.mp4',
                description: 'Драконид',
				descriptionfull: 'Фениксы известны уникальной способностью возрождаться с помощью пепла и эмбриона, развивающегося в их собственных животах.',
				ability: 'eredin_ability',
                position: 'ranged-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'bronze',
                tags: ['monster'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
			{
                id: 'monsters_unit_7',
                name: 'Морвудд',
				namefull: 'Морвудд',
                strength: 5,
                type: 'unit',
                faction: 'monsters',
                image: 'morvudd.mp4',
                description: 'Бес',
				descriptionfull: 'Тигровый бес, подвид имеет отличный от иных бесов цвет шерсти и полоски на теле, и проживает на самом крупном острове архипелага Скеллиге.',
				ability: 'eredin_ability',
                position: 'ranged-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'bronze',
                tags: ['monster'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
        ],
        specials: [
            {
                id: 'monsters_special_1',
                name: 'Белый Хлад',
                type: 'special',
                faction: 'monsters',
                image: 'cold.mp4',
                description: 'Природа',
				descriptionfull: 'Это Час Конца. Мир, уничтоженный Белым Хладом.',
				ability: 'biting_frost',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
		],
        tactics: [],
		artifacts: [
            {
                id: 'monsters_artifact_1',
                name: 'Книга некроманта',
                type: 'artifact',
                faction: 'monsters',
                image: 'book.mp4',
                description: 'Артефакт',
				descriptionfull: 'Некоторые страницы изготовлены из человеческой кожи, а многочисленные пророчества, похоронные обряды и ритуалы воскрешения записаны кровью.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
            {
                id: 'monsters_artifact_2',
                name: 'Руна Девана',
                type: 'artifact',
                faction: 'monsters',
                image: 'devan.mp4',
                description: 'Артефакт',
				descriptionfull: 'Мое острие ранит... все острее!',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
            {
                id: 'monsters_artifact_3',
                name: 'Урна теней',
                type: 'artifact',
                faction: 'monsters',
                image: 'urna.mp4',
                description: 'Артефакт',
				descriptionfull: 'Тьма таится в каждом. Некоторые умеют подчинять ее своей воле…',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
		]
    },

    nilfgaard: {
        units: [
            {
                id: 'nilfgaard_unit_1',
                name: 'Эмгыр',
				namefull: 'Эмгыр вар Эмрейс',
                strength: 10,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'emhyr.mp4',
                description: 'IV Император Нильфгаарда',
				descriptionfull: 'Эмгыр вар Эмрейс ради власти был готов на всё. Развязать войну. Убить собственную жену. Причинить вред собственной дочери. И всё это не повышая голоса, без единой слезинки. Его поблекшие холодные глаза не отражали никаких эмоций. Говорили, что даже у служивших в имперской армии големов было больше чувств, чем у него…',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['leader', 'emperor'],
                border: 'deck/bord_gold.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_2',
                name: 'Воорхис',
				namefull: 'Морвран Воорхис',
                strength: 7,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'morvran.mp4',
                description: 'V Император Нильфгаарда',
				descriptionfull: 'Воорхис обычно говаривал, что не нуждается в мече, чтобы выигрывать войны. И в этих словах было много правды. Он строил свою стратегию на шпионах, саботажниках и диверсантах. Возможно, это было не слишком достойно, зато эффективно.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['emperor'],
                border: 'deck/bord_gold.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_3',
                name: 'Ян Кальвейт',
				namefull: 'Ян Кальвейт',
                strength: 7,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'yan.mp4',
                description: 'VI Император Нильфгаарда',
				descriptionfull: 'Ян Кальвейт привык наблюдать за сражением, сидя на складном стуле на самом краю поля боя. Он не вставал с него, даже когда вокруг падали горящие стрелы или камни вражеских катапульт. «Все мы когда-нибудь умрем, — говаривал он. — Мой день ещё не настал».',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['emperor'],
                border: 'deck/bord_gold.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_4',
                name: 'Узурпатор',
				namefull: 'Узурпатор',
                strength: 5,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'usurper.mp4',
                description: 'III Император Нильфгаарда',
				descriptionfull: 'Узурпатор был главарём заговора, в результате которого погиб Фергус вар Эмрейс, а его сын, Эмгыр, подвергся нечеловеческим пыткам. Мы немногое знаем об Узурпаторе. Даже имя его неизвестно. Об этом позаботился Эмгыр вар Эмрейс, который убил Узурпатора и занял его место.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['emperor'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
            {
                id: 'nilfgaard_unit_5',
                name: 'Вильгефорц',
				namefull: 'Вильгефорц из Роггевеена',
                strength: 6,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'vilgefortz.mp4',
                description: 'Лидер Капитула Чародеев',
				descriptionfull: 'Могущественный чародей и исследователь, в прошлом ― наёмник и друид, член и один из лидеров Капитула Чародеев и фактический виновник и организатор Танеддского бунта. ',
				ability: '---',
                position: 'siege-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'silver',
                tags: ['mage'],
                border: 'deck/bord_silver.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_6',
                name: 'Иоахим',
				namefull: 'Иоахим де Ветт',
                strength: 5,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'wett.mp4',
                description: 'Герцог',
				descriptionfull: 'Иоахим был недоволен политикой Эмгыра и втайне мечтал о свержении самодержца.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'silver',
                tags: ['soldier'],
                border: 'deck/bord_silver.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
			{
                id: 'nilfgaard_unit_7',
                name: 'Лето',
				namefull: 'Лето из Гулеты',
                strength: 8,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'leto.mp4',
                description: 'Убийца королей',
				descriptionfull: 'Опытный и бывалый ведьмак школы Змеи, знающий цену себе и своим способностям. Он смел, уверен в себе, умеет быть как мстительным, так и благодарным, а его чувство юмора нервирует даже его соратников. Лето хладнокровен и довольно сдержан в проявлении эмоций, хотя и не скрывает своего отношения к определённым ситуациям.',
				ability: '---',
                position: 'any-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'silver',
                tags: ['witcher'],
                border: 'deck/bord_silver.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
        ],
        specials: [],
        tactics: [
			{
                id: 'nilfgaard_tactic_1',
                name: 'Рекрут',
                type: 'tactic',
                faction: 'nilfgaard',
                image: 'recruit.mp4',
                description: 'Солдат',
				descriptionfull: 'Кто-то же должен чистить картошку, чтоб остальные могли сражаться.',
				ability: 'morale_boost',
                rarity: 'bronze',
                tags: ['tactic'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
		],
        artifacts: [
            {
                id: 'nilfgaard_artifact_1',
                name: 'Обсидиановое зеркальце',
                type: 'artifact',
                faction: 'nilfgaard',
                image: 'obsidian.mp4',
                description: 'Артефакт',
				descriptionfull: 'Не стоит слишком долго вглядываться в мягкое сияние обсидиана, ибо неизвестно, что уставится на вас в ответ.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
            {
                id: 'nilfgaard_artifact_2',
                name: 'Руна Даждьбог',
                type: 'artifact',
                faction: 'nilfgaard',
                image: 'dazhdbog.mp4',
                description: 'Артефакт',
				descriptionfull: 'Эта руна, горячее любого пламени.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
            {
                id: 'nilfgaard_artifact_3',
                name: 'Рабский ошейник',
                type: 'artifact',
                faction: 'nilfgaard',
                image: 'rab.mp4',
                description: 'Артефакт',
				descriptionfull: 'У тех, кто оказывается в долгу у Ван Мурлегемов, остается два варианта: податься в рабство или свести счеты с жизнью. Те, кто поумнее, выбирают второй вариант…',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
		]
    },

    realms: {
        units: [
            {
                id: 'realms_unit_1',
                name: 'Фольтест',
				namefull: 'Фольтест Темерский',
                strength: 10,
                type: 'unit',
                faction: 'realms',
                image: 'foltest.mp4',
                description: 'Король Темерии',
				descriptionfull: 'Предводитель Севера, князь Соддена, правитель Понтарии, сюзерен Махакама и сеньор-протектор Бругге, Ангрена, Заречья и Элландера. И не сосчитать все титули и звания его величества. В ходе своего правления значительно укрепил и стабилизировал страну, установил твёрдую королевскую власть и поддерживал политическую стабильность.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'gold',
                tags: ['leader', 'king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/realms/banner_gold.png'
            },
            {
                id: 'realms_unit_2',
                name: 'Радовид V',
				namefull: 'Радовид V Свирепый',
                strength: 9,
                type: 'unit',
                faction: 'realms',
                image: 'radovid.mp4',
                description: 'Король Редании',
				descriptionfull: 'По праву считается одним из могущественнейших правителей Севера. Он строгий и суровый владыка, наделённый несгибаемой волей и твёрдым нравом. При этом он спокоен и рассудителен, при отдаче приказов ему нет нужды повышать голос — люди и без того чувствуют его холодную силу и непоколебимую уверенность в себе.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/realms/banner_gold.png'
            },
            {
                id: 'realms_unit_3',
                name: 'Хенсельт',
				namefull: 'Хенсельт из Ард Каррайга',
                strength: 9,
                type: 'unit',
                faction: 'realms',
                image: 'henselt.mp4',
                description: 'Король Каэдвена',
				descriptionfull: 'Хенсельт из Ард Каррайга, по прозвищу Единорог — был талантливым полководцем, не сделал Каэдвен могучей державой. Он не смог ни найти себе союзников, ни закрепить успех после побед. Впрочем, это его не особенно волновало. Он сражался, чтобы сражаться.',
				ability: '---',
                position: 'any-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/realms/banner_gold.png'
            },
            {
                id: 'realms_unit_4',
                name: 'Стеннис',
				namefull: 'Принц Стеннис',
                strength: 5,
                type: 'unit',
                faction: 'realms',
                image: 'stennis.mp4',
                description: 'Принц Аэдирна',
				descriptionfull: 'Личность Стенниса достаточно сложна и неоднозначна. Прежде всего, принц Стеннис — гордый и уверенный в себе аристократ, убеждённый в своей правоте и достоинстве как наследника престола Аэдирна.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'bronze',
                tags: ['king'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_unit_5',
                name: 'Вернон Роше',
				namefull: 'Вернон Роше',
                strength: 7,
                type: 'unit',
                faction: 'realms',
                image: 'roche.mp4',
                description: 'Безжалостный убийца',
				descriptionfull: 'Глава темерского военизированного спецподразделения «Синие Полоски» и доверенное лицо короля Фольтеста.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'bronze',
                tags: ['soldier'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_unit_6',
                name: 'Адда Белая',
				namefull: 'Принцесса Адда',
                strength: 6,
                type: 'unit',
                faction: 'realms',
                image: 'adda.mp4',
                description: 'Проклятая принцесса Темерии',
				descriptionfull: 'Темерская принцесса, дочь короля Фольтеста, подвергнувшаяся проклятию и превращённая в стрыгу.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'bronze',
                tags: ['kingser'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
        ],
        specials: [
            {
                id: 'realms_special_1',
                name: 'Руническое слово',
                type: 'special',
                faction: 'realms',
                image: 'runes.mp4',
                description: 'Заклинание',
				descriptionfull: 'Лучше не произносить его вслух.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['spell'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
		],
        tactics: [
            {
                id: 'realms_tactic_1',
                name: 'Подкрипление',
                type: 'tactic',
                faction: 'realms',
                image: 'tactic.mp4',
                description: 'Тактика',
				descriptionfull: 'Трубить отступление! Перегруппироваться и ждать подкрепления!',
				ability: 'morale_boost',
                rarity: 'bronze',
                tags: ['tactic'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
		],
        artifacts: [
            {
                id: 'realms_artifact_1',
                name: 'Меч Вандергрифта',
                type: 'artifact',
                faction: 'realms',
                image: 'sword.mp4',
                description: 'Артефакт',
				descriptionfull: 'На рыцарском турнире в Ард Каррайге Зельткирк разломал меч Вандергрифта. После этого взбешенный Вандергрифт заказал себе колдовской клинок, зачарованный могущественными рунами.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_artifact_2',
                name: 'Руна Зоря',
                type: 'artifact',
                faction: 'realms',
                image: 'zorya.mp4',
                description: 'Артефакт',
				descriptionfull: 'От этой руны веет неестественным холодом. Может, кто-то когда-то ранил ее чувства?',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_artifact_3',
                name: 'Кровавый бич',
                type: 'artifact',
                faction: 'realms',
                image: 'blood.mp4',
                description: 'Артефакт',
				descriptionfull: 'Некоторые виды оружия были запрещены в королевствах Севера — столь страшны были раны, нанесенные ими.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
		]
    },

    scoiatael: {
        units: [
            {
                id: 'scoiatael_unit_1',
                name: 'Францеска',
				namefull: 'Францеска Финдабаир',
                strength: 10,
                type: 'unit',
                faction: 'scoiatael',
                image: 'francesca.mp4',
                description: 'Княгиня Дол Блатанны',
				descriptionfull: 'Известная как Маргаритка из Долин. Сильный политический игрок, она умеет плести интриги, хорошо разбирается в нюансах настроений высшего общества Севера, к которому принадлежит. Хитра как лисица и сделает всё ради блага своего народа.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['mage', 'leader'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
            {
                id: 'scoiatael_unit_2',
                name: 'Филавандрель',
				namefull: 'Филавандрель',
                strength: 9,
                type: 'unit',
                faction: 'scoiatael',
                image: 'filavandrel.mp4',
                description: 'Предводитель эльфов Синих гор',
				descriptionfull: 'В отличие от многих других эльфов, Филавандрель не жил под людским игом, ему не приходилось терпеть унижения и бояться погромов. Он держится так гордо потому, что никто и никогда не принуждал его кланяться.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
            {
                id: 'scoiatael_unit_3',
                name: 'Брувер',
				namefull: 'Брувер Гоог',
                strength: 9,
                type: 'unit',
                faction: 'scoiatael',
                image: 'goog.mp4',
                description: 'Старейшина Махакама',
				descriptionfull: 'Старейшина Махакама, который сумел спасти свой народ и привел его к процветанию. Брувер не только опытный политик, но и хороший воин: если понадобится, он прибегнет к помощи своего верного боевого топора, несмотря на высокое положение.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
            {
                id: 'scoiatael_unit_4',
                name: 'Эитнэ',
				namefull: 'Эитнэ',
                strength: 9,
                type: 'unit',
                faction: 'scoiatael',
                image: 'eitne.mp4',
                description: 'Правительница Брокилона',
				descriptionfull: 'Древняя, как сам Брокилон, Эитнэ ― повелительница дриад, не покидающая своей обители в Дуэн Канэлл. Она не признаёт всё, что относится к людям, и пренебрежительно относится к королевствам, находящимся близ границ её леса.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
			{
                id: 'scoiatael_unit_6',
                name: 'Эльфская разведчица',
				namefull: 'Эльфская разведчица',
                strength: 4,
                type: 'unit',
                faction: 'scoiatael',
                image: 'scout.mp4',
                description: 'Эльфийка',
				descriptionfull: 'Говорят, что эльфы не оставляют следов на снегу. Но сдается мне, что это лишь болтовня сельских дурачков.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['soldier'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
			{
                id: 'scoiatael_unit_7',
                name: 'Эльдайн',
				namefull: 'Эльдайн',
                strength: 8,
                type: 'unit',
                faction: 'scoiatael',
                image: 'eldains.mp4',
                description: 'Командир отряда Скоя\'таэлей',
				descriptionfull: 'Эльдайн не носил никаких доспехов, не признавал щита. Он скользил по полю боя с грацией танцора, едва касаясь земли, без труда уклоняясь от ударов.',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['soldier'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
        ],
        specials: [
            {
                id: 'scoiatael_special_1',
                name: 'Круг жизни',
                type: 'special',
                faction: 'scoiatael',
                image: 'life.mp4',
                description: 'Проклятье',
				descriptionfull: 'Те, кто хочет сровнять Брокилон с землей, сжечь его деревья и погубить в нем все живое, скоро станут пищей для его почвы.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['spell'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
            {
                id: 'scoiatael_special_2',
                name: 'Зов леса',
                type: 'special',
                faction: 'scoiatael',
                image: 'voise.mp4',
                description: 'Призыв',
				descriptionfull: 'Брокилон для меня дороже жизни. Мы его дети, и он заботится о нас. Я буду защищать его до последнего вздоха.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['spell'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
		],
        tactics: [],
        artifacts: [
            {
                id: 'scoiatael_artifact_1',
                name: 'Махакамский рог',
                type: 'artifact',
                faction: 'scoiatael',
                image: 'rog.mp4',
                description: 'Артефакт',
				descriptionfull: 'Как-то раз в Махакаме устроили конкурс игры на роге. И тогда краснолюды обнаружили, что громкие звуки и покрытые снегом вершины — не самое удачное сочетание.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
            {
                id: 'scoiatael_artifact_2',
                name: 'Руна Марена',
                type: 'artifact',
                faction: 'scoiatael',
                image: 'marena.mp4',
                description: 'Артефакт',
				descriptionfull: 'Даже смотреть противно.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
            {
                id: 'scoiatael_artifact_3',
                name: 'Шар видения',
                type: 'artifact',
                faction: 'scoiatael',
                image: 'vision.mp4',
                description: 'Артефакт',
				descriptionfull: 'В нем виден лишь один вариант будущего из многих.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
		]
    },

    skellige: {
        units: [
            {
                id: 'skellige_unit_1',
                name: 'Бран',
				namefull: 'Бран Тиршах',
                strength: 10,
                type: 'unit',
                faction: 'skellige',
                image: 'bran.mp4',
                description: 'Конунг Скеллиге',
				descriptionfull: 'Говорят, будто легче обуздать море, что омывает берега Скеллиге, чем самих его жителей. Но Брану это удалось. Он подчинил себе Острова — и правил ими железной рукой.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['leader', 'king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
            {
                id: 'skellige_unit_2',
                name: 'Эйст',
				namefull: 'Эйст Тиршах',
                strength: 9,
                type: 'unit',
                faction: 'skellige',
                image: 'eist.mp4',
                description: 'Ярл клана Тиршах',
				descriptionfull: 'Эйст приходился братом королю Скеллиге Брану Тиршаху, а также дядей ярлу Краху ан Крайту',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
            {
                id: 'skellige_unit_3',
                name: 'Крах',
				namefull: 'Крах ан Крайт',
                strength: 9,
                type: 'unit',
                faction: 'skellige',
                image: 'krah.mp4',
                description: 'Ярл клана ан Крайт',
				descriptionfull: 'Имена многих вождей и героев Скеллиге увековечены в сагах, но ни один из них не был столь славен, как Крах, ярл клана Крайт и правитель Каэр Трольде. Скальды воспевали его силу, отвагу, благоразумие, щедрость, верность друзьям и беспощадность к врагам.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
            {
                id: 'skellige_unit_4',
                name: 'Харальд Хромой',
				namefull: 'Харальд Хромой',
                strength: 9,
                type: 'unit',
                faction: 'skellige',
                image: 'harald.mp4',
                description: 'Древний конунг Скеллиге',
				descriptionfull: 'Харальд был посредственным воином, пока однажды медведь не покалечил ему ногу. Кость срослась криво, боль преследовала его до конца дней, но… Харальд стал сражаться лучше, чем прежде.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
			{
                id: 'skellige_unit_5',
                name: 'Фламиника',
				namefull: 'Фламиника',
                strength: 5,
                type: 'unit',
                faction: 'skellige',
                image: 'flaminica.mp4',
                description: 'Друин клана Хэймэй',
				descriptionfull: 'Фламиника — предводительница круга друидов',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['soldier', 'mage'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
			{
                id: 'skellige_unit_6',
                name: 'Керис',
				namefull: 'Керис ан Крайт',
                strength: 6,
                type: 'unit',
                faction: 'skellige',
                image: 'cerys.mp4',
                description: 'Неустрашимая',
				descriptionfull: 'Как и её отец, Керис умна, хитра, решительна и упряма. В отличие от своего брата, она куда более обстоятельно обдумывает свои действия и не идёт напролом.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['kingser'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
			{
                id: 'skellige_unit_7',
                name: 'Хольгер',
				namefull: 'Хольгер Чернорукий',
                strength: 6,
                type: 'unit',
                faction: 'skellige',
                image: 'blackhand.mp4',
                description: 'Ярл клана Димун',
				descriptionfull: 'Хольгер известен своей жестокостью и кровожадностью. Он предводительствует кланом, даже по меркам островитян славящимся свирепостью и безжалостностью.',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['kingser'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
        ],
        specials: [
            {
                id: 'skellige_special_1',
                name: 'Шторм Скеллиге',
                type: 'special',
                faction: 'skellige',
                image: 'storm.mp4',
                description: 'Природа',
				descriptionfull: 'Это не простая буря. Это гнев богов.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
		],
        tactics: [],
        artifacts: [
            {
                id: 'skellige_artifact_1',
                name: 'Магический компас',
                type: 'artifact',
                faction: 'skellige',
                image: 'compas.mp4',
                description: 'Артефакт',
				descriptionfull: 'Поможет найти искомое, даже если оно не очень-то вам и нужно.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
            {
                id: 'skellige_artifact_2',
                name: 'Руна Стрибог',
                type: 'artifact',
                faction: 'skellige',
                image: 'stribog.mp4',
                description: 'Артефакт',
				descriptionfull: 'Офирские мастера умеют складывать из слов руны, наделенные большой силой.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
            {
                id: 'skellige_artifact_3',
                name: 'Слезы сирены',
                type: 'artifact',
                faction: 'skellige',
                image: 'sirena.mp4',
                description: 'Артефакт',
				descriptionfull: 'Говорят, мол, они плачут только по утерянной любви. Жалко, что влюбляются они раз и на всю жизнь...',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
		]
    },
	
	syndicate: {
        units: [
            {
                id: 'syndicate_unit_1',
                name: 'Тесак',
				namefull: 'Карл Варезе',
                strength: 10,
                type: 'unit',
                faction: 'syndicate',
                image: 'vareze.mp4',
                description: 'Лидер группировки «Златорубов»',
				descriptionfull: 'Карло Варезе по прозвищу Тесак — вспыльчивый главарь Златорубов. Это безжалостные «деловые краснолюды», которые постоянно ищут новые возможности.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'gold',
                tags: ['leader', 'king', 'Краснолюд'],
                border: 'deck/bord_gold.png',
                banner: 'faction/syndicate/banner_gold.png'
            },
            {
                id: 'syndicate_unit_2',
                name: 'Ублюдок Младший',
				namefull: 'Киприан Вилли',
                strength: 9,
                type: 'unit',
                faction: 'syndicate',
                image: 'villi.mp4',
                description: 'Лидер группировки «Сердцеедов»',
				descriptionfull: 'Киприан Вилли, известный в городе как Ублюдок Младший, ведет за собой жестоких и беспощадных Сердцеедов — это шайка садистов, которые готовы замучить любого, кто перейдет им дорогу.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'silver',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/syndicate/banner_gold.png'
            },
            {
                id: 'syndicate_unit_3',
                name: 'Король Нищих',
				namefull: 'Франциск Бедлам',
                strength: 9,
                type: 'unit',
                faction: 'syndicate',
                image: 'bedlam.mp4',
                description: 'Лидер группировки «Невидимых»',
				descriptionfull: 'Франциск Бедлам, известный как Король Нищих, полагается на свою банду Невидимых. Мелкие воришки, продажные женщины, попрошайки и все, кого народ привык не замечать, занимаются лишь тем, что разнюхивают для Короля информацию — главный источник его власти.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'silver',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/syndicate/banner_gold.png'
            },
            {
                id: 'syndicate_unit_4',
                name: 'Сиги Ройвен',
				namefull: 'Сигизмунд Дийкстра',
                strength: 9,
                type: 'unit',
                faction: 'syndicate',
                image: 'dijkstra.mp4',
                description: 'Лидер группировки «Сиги Ройвена»',
				descriptionfull: 'Член правления Синдиката. Бывший шеф реданской разведки. Именуется графом, дабы не вызывать у окружения подозрений и недоброжелательности',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'silver',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/syndicate/banner_gold.png'
            },
			{
                id: 'syndicate_unit_5',
                name: 'Яков',
				namefull: 'Яков из Альдерсберга',
                strength: 6,
                type: 'unit',
                faction: 'syndicate',
                image: 'jakub.mp4',
                description: 'Магистр Ордена Пылающей Розы',
				descriptionfull: 'Желая заполучить в свою армию сильнейших солдат, Великий Магистр заключает сделку с Саламандрами- Вызимской бандой убийц и наркоторговцев, во главе с мятежным Зерриканским чародеем Азаром Яведом ',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'silver',
                tags: ['leader'],
                border: 'deck/bord_silver.png',
                banner: 'faction/syndicate/banner_bronze.png'
            },
			{
                id: 'syndicate_unit_6',
                name: 'Тинбой',
				namefull: 'Тинбой',
                strength: 4,
                type: 'unit',
                faction: 'syndicate',
                image: 'tinboy.mp4',
                description: 'Лидер группы бандитов Короля Нищих',
				descriptionfull: 'Батя его был лудильщиком. И когда был трезвый, лудил по металлу. А когда пьяный — бывало, и по лицу сынка.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'bronze',
                tags: ['soldier'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/syndicate/banner_bronze.png'
            },
			{
                id: 'syndicate_unit_7',
                name: 'Клоук-фрик',
				namefull: 'Клоук-фрик',
                strength: 4,
                type: 'unit',
                faction: 'syndicate',
                image: 'freak.mp4',
                description: 'Фрик из шой уродов Ублюдка младшего',
				descriptionfull: 'Ты чё такой серьёзный?',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'bronze',
                tags: ['soldier'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/syndicate/banner_bronze.png'
            },
			{
                id: 'syndicate_unit_8',
                name: 'Великий инквизитор',
				namefull: 'Гелвид',
                strength: 6,
                type: 'unit',
                faction: 'syndicate',
                image: 'helveed.mp4',
                description: 'Инквизитор Ордена Пылающей Розы',
				descriptionfull: 'Значимый церковный деятель из Новиграда. По статусу и положении он идет сразу после самого Иерарха.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'bronze',
                tags: ['soldier'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/syndicate/banner_bronze.png'
            },
			{
                id: 'syndicate_unit_9',
                name: 'Гвитр и Аэлидия',
				namefull: 'Гвитр и Аэлидия',
                strength: 5,
                type: 'unit',
                faction: 'syndicate',
                image: 'hvitr_and_aelydia.mp4',
                description: 'Пираты из организация «Теней прилива»',
				descriptionfull: 'Они неразделимы, непобедимы и ненадёжны.',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/syndicate/banner_position.png',
                rarity: 'silver',
                tags: ['soldier'],
                border: 'deck/bord_silver.png',
                banner: 'faction/syndicate/banner_bronze.png'
            },
        ],
        specials: [],
        tactics: [
            {
                id: 'syndicate_tactic_1',
                name: 'Сговор',
                type: 'tactic',
                faction: 'syndicate',
                image: 'collusion.mp4',
                description: 'Тактика',
				descriptionfull: 'В этом городе золота хватит всем. Ну, нам-то уж точно хватит.',
				ability: 'morale_boost',
                rarity: 'bronze',
                tags: ['tactic'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/syndicate/banner_bronze.png'
            },
		],
        artifacts: [
            {
                id: 'syndicate_artifact_1',
                name: 'Священное пламя',
                type: 'artifact',
                faction: 'syndicate',
                image: 'flame.mp4',
                description: 'Артефакт',
				descriptionfull: 'Вечный Огонь — символ надежды, стойкости к несчастьям, света, указывающего путь во тьме, предвещающего прогресс и лучшее завтра.',
				ability: 'torrential_rain',
                rarity: 'silver',
                tags: ['artifact'],
                border: 'deck/bord_silver.png',
                banner: 'faction/syndicate/banner_bronze.png'
            },]
    },
};

function normalizeCardPositions(cards) {
    return cards.map(card => {
        if (card.position && Array.isArray(card.position) && card.position.length > 1) {
            return {
                ...card,
                position: ['any-row']
            };
        }
        return card;
    });
}

Object.keys(cardsData).forEach(faction => {
    Object.keys(cardsData[faction]).forEach(type => {
        if (Array.isArray(cardsData[faction][type])) {
            cardsData[faction][type] = normalizeCardPositions(cardsData[faction][type]);
        }
    });
});

function getFactionCards(factionId) {
    const factionCards = {
        units: [...cardsData[factionId].units],
        specials: [...cardsData[factionId].specials],
        artifacts: [...cardsData[factionId].artifacts],
        tactics: [...cardsData[factionId].tactics] 
    };

    factionCards.units.push(...cardsData.neutral.units);
    factionCards.specials.push(...cardsData.neutral.specials);
    factionCards.artifacts.push(...cardsData.neutral.artifacts);
    factionCards.tactics.push(...cardsData.neutral.tactics || []);

    return factionCards;
}

function getCardById(cardId) {
    for (const faction in cardsData) {
        for (const type in cardsData[faction]) {
            const card = cardsData[faction][type].find(c => c.id === cardId);
            if (card) return card;
        }
    }
    return null;
}

function getCardsByTag(tag) {
    const result = {
        units: [],
        specials: [],
        artifacts: []
    };

    for (const faction in cardsData) {
        for (const type in cardsData[faction]) {
            cardsData[faction][type].forEach(card => {
                if (card.tags && card.tags.includes(tag)) {
                    result[type].push(card);
                }
            });
        }
    }

    return result;
}

function getAllCards() {
    return cardsData;
}

window.cardsModule = {
    getFactionCards,
    getCardById,
    getCardsByTag,
    getAllCards,
    cardsData
};