const cardsData = {
    neutral: {
        units: [
            {
                id: 'neutral_unit_1',
                name: 'Геральт',
				namefull: 'Геральт из Ривии',
                strength: 10,
                type: 'unit',
                faction: 'neutral',
                image: 'geralt.mp4',
                description: 'Ведьмак школы Волка',
				descriptionfull: '---',
				ability: 'geralt',
                position: 'any-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
            {
                id: 'neutral_unit_2',
                name: 'Весемир',
				namefull: 'Весемир',
                strength: 7,
                type: 'unit',
                faction: 'neutral',
                image: 'vesemir.mp4',
                description: 'Наставник ведьмаков школы Волка',
				descriptionfull: '---',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'silver',
                tags: ['witcher'],
                border: 'deck/bord_silver.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_unit_3',
                name: 'Цири',
				namefull: 'Цирилла Фиона Элен Рианнон',
                strength: 9,
                type: 'unit',
                faction: 'neutral',
                image: 'ciri.mp4',
                description: 'Ведьмачка школы Волка',
				descriptionfull: '---',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['witcher'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
            {
                id: 'neutral_unit_4',
                name: 'Йеннифэр',
				namefull: 'Йеннифэр из Венгерберга',
                strength: 6,
                type: 'unit',
                faction: 'neutral',
                image: 'yennifer.mp4',
                description: 'Чародейка',
				descriptionfull: '---',
				ability: '---',
                position: 'siege-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['mage'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
            {
                id: 'neutral_unit_5',
                name: 'Трисс',
				namefull: 'Трисс Меригольд',
                strength: 8,
                type: 'unit',
                faction: 'neutral',
                image: 'triss.mp4',
                description: 'Чародейка',
				descriptionfull: '---',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/neutral/banner_position.png',
                rarity: 'gold',
                tags: ['mage'],
                border: 'deck/bord_gold.png',
                banner: 'faction/neutral/banner_gold.png'
            },
        ],
        specials: [
            {
                id: 'neutral_special_1',
                name: 'Проливной дождь',
                type: 'special',
                faction: 'neutral',
                image: 'rain.mp4',
                description: 'Погода',
				descriptionfull: 'Создайте эффект дождя в ряду противника на 3 хода',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_special_2',
                name: 'Трескучий мороз',
                type: 'special',
                faction: 'neutral',
                image: 'cold.mp4',
                description: 'Погода',
				descriptionfull: 'Создайте эффект мороза в ряду противника на 3 хода',
				ability: 'impenetrable_fog',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_special_3',
                name: 'Густой туман',
                type: 'special',
                faction: 'neutral',
                image: 'fog.mp4',
                description: 'Погода',
				descriptionfull: 'Создайте эффект тумана в ряду противника на 3 хода',
				ability: 'impenetrable_fog',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
            {
                id: 'neutral_special_4',
                name: 'Чистое небо',
                type: 'special',
                faction: 'neutral',
                image: 'sun.mp4',
                description: 'Погода',
				descriptionfull: '----',
				ability: 'clear_weather',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/neutral/banner_bronze.png'
            },
		],
        tactics: [],
        artifacts: [],
    },

    monsters: {
        units: [
            {
                id: 'monsters_unit_1',
				name: 'Эредин',
				namefull: 'Эредин Бреакк Глас',
				strength: 10,
				type: 'unit',
				faction: 'monsters',
				image: 'eredin.mp4',
				description: 'Командир Дикой Охоты',
				descriptionfull: 'Эредин Бреакк Глас - король Ольх и командир Дикой Охоты. Беспощадный воин, ведущий свою армию через миры в поисках новых земель для завоевания.',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
				rarity: 'gold',
				tags: ['leader', 'wild_hunt'],
				border: 'deck/bord_gold.png',
				banner: 'faction/monsters/banner_gold.png'
            },
            {
                id: 'monsters_unit_2',
                name: 'Имлерих',
				namefull: 'Имлерих',
                strength: 9,
                type: 'unit',
                faction: 'monsters',
                image: 'imlerih.mp4',
                description: 'Полководец Дикой Охоты',
				descriptionfull: 'Беспощадный воин, ведущий свою армию через миры в поисках новых земель для завоевания.',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
				rarity: 'gold',
                tags: ['wild_hunt'],
                border: 'deck/bord_gold.png',
                banner: 'faction/monsters/banner_gold.png'
            },
            {
                id: 'monsters_unit_3',
                name: 'Карантир',
				namefull: 'Карантир Ар-Фейниэль',
                strength: 6,
                type: 'unit',
                faction: 'monsters',
                image: 'karantir.mp4',
                description: 'Лейтенант Дикой Охоты',
				descriptionfull: 'Беспощадный воин, ведущий свою армию через миры в поисках новых земель для завоевания.',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'gold',
                tags: ['wild_hunt'],
                border: 'deck/bord_gold.png',
                banner: 'faction/monsters/banner_gold.png'
            },
            {
                id: 'monsters_unit_4',
                name: 'Нитраль',
				namefull: 'Нитраль',
                strength: 6,
                type: 'unit',
                faction: 'monsters',
                image: 'nitral.mp4',
                description: 'Всадник Дикой Охоты',
				descriptionfull: 'Беспощадный воин, ведущий свою армию через миры в поисках новых земель для завоевания.',
				ability: 'eredin_ability',
                position: 'close-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'gold',
                tags: ['wild_hunt'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
			{
                id: 'monsters_unit_5',
                name: 'Хим',
				namefull: 'Хим',
                strength: 3,
                type: 'unit',
                faction: 'monsters',
                image: 'hym.mp4',
                description: 'Дух страха',
				descriptionfull: 'Боги обращаются ко мне. Я слышу их шепот из тени....',
				ability: 'eredin_ability',
                position: 'ranged-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'bronze',
                tags: ['monster'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
			{
                id: 'monsters_unit_6',
                name: 'Феникс',
				namefull: 'Феникс',
                strength: 5,
                type: 'unit',
                faction: 'monsters',
                image: 'phoenix.mp4',
                description: 'Драконид',
				descriptionfull: 'Вопрос, что было первым, курица или яйцо, приобретает новый смысл в случае с фениксами.',
				ability: 'eredin_ability',
                position: 'ranged-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'bronze',
                tags: ['monster'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
			{
                id: 'monsters_unit_7',
                name: 'Морвудд',
				namefull: 'Морвудд',
                strength: 5,
                type: 'unit',
                faction: 'monsters',
                image: 'morvudd.mp4',
                description: 'Реликт',
				descriptionfull: '---',
				ability: 'eredin_ability',
                position: 'ranged-row',
                positionBanner: 'faction/monsters/banner_position.png',
                rarity: 'bronze',
                tags: ['monster'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
        ],
        specials: [
            {
                id: 'monsters_special_1',
                name: 'Белый Хлад',
                type: 'special',
                faction: 'monsters',
                image: 'cold.mp4',
                description: 'Природа',
				descriptionfull: 'Уничтожьте слабейший отряд. Если вы не применили способности Приказ на этом ходу - уничтожьте все слабейшие отряды',
				ability: 'biting_frost',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
		],
        tactics: [],
		artifacts: [
            {
                id: 'monsters_artifact_1',
                name: 'Книга некроманта',
                type: 'artifact',
                faction: 'monsters',
                image: 'book.mp4',
                description: 'Артефакт',
				descriptionfull: 'Каждый раз, когда играете бронзовый отряд, призывайте его случайную копию из вашего сброса в тот же ряд и добавляйте ей обреченность',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
            {
                id: 'monsters_artifact_2',
                name: 'Руна Девана',
                type: 'artifact',
                faction: 'monsters',
                image: 'devan.mp4',
                description: 'Артефакт',
				descriptionfull: 'Сыграйте бронзовую карту Чудовища',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
            {
                id: 'monsters_artifact_3',
                name: 'Урна теней',
                type: 'artifact',
                faction: 'monsters',
                image: 'urna.mp4',
                description: 'Артефакт',
				descriptionfull: 'Активируйте способность Завещание у дружественного отряда',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/monsters/banner_bronze.png'
            },
		]
    },

    nilfgaard: {
        units: [
            {
                id: 'nilfgaard_unit_1',
                name: 'Эмгыр',
				namefull: 'Эмгыр вар Эмрейс',
                strength: 10,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'emhyr.mp4',
                description: 'IV Император Нильфгаарда',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['leader', 'emperor'],
                border: 'deck/bord_gold.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_2',
                name: 'Воорхис',
				namefull: 'Морвран Воорхис',
                strength: 7,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'morvran.mp4',
                description: 'V Император Нильфгаарда',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['emperor'],
                border: 'deck/bord_gold.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_3',
                name: 'Кальвейт',
				namefull: 'Ян Кальвейт',
                strength: 7,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'yan.mp4',
                description: 'VI Император Нильфгаарда',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['emperor'],
                border: 'deck/bord_gold.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_4',
                name: 'Узурпатор',
				namefull: 'Узурпатор',
                strength: 5,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'usurper.mp4',
                description: 'III Император Нильфгаарда',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'gold',
                tags: ['emperor'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
            {
                id: 'nilfgaard_unit_5',
                name: 'Вильгефорц',
				namefull: 'Вильгефорц из Роггевеена',
                strength: 6,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'vilgefortz.mp4',
                description: 'Чародей',
				descriptionfull: '---',
				ability: '---',
                position: 'siege-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'silver',
                tags: ['mage'],
                border: 'deck/bord_silver.png',
                banner: 'faction/nilfgaard/banner_gold.png'
            },
            {
                id: 'nilfgaard_unit_6',
                name: 'Иоахим',
				namefull: 'Иоахим де Ветт',
                strength: 5,
                type: 'unit',
                faction: 'nilfgaard',
                image: 'wett.mp4',
                description: 'Герцог де Ветт',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/nilfgaard/banner_position.png',
                rarity: 'silver',
                tags: ['soldier'],
                border: 'deck/bord_silver.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
        ],
        specials: [],
        tactics: [
			{
                id: 'nilfgaard_tactic_1',
                name: 'Рекрут',
                type: 'tactic',
                faction: 'nilfgaard',
                image: 'recruit.mp4',
                description: 'Солдат',
				descriptionfull: 'Кто-то же должен чистить картошку, чтоб остальные могли сражаться.',
				ability: 'morale_boost',
                rarity: 'bronze',
                tags: ['tactic'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
		],
        artifacts: [
            {
                id: 'nilfgaard_artifact_1',
                name: 'Обсидиановое зеркальце',
                type: 'artifact',
                faction: 'nilfgaard',
                image: 'obsidian.mp4',
                description: 'Артефакт',
				descriptionfull: 'Создайте копии 3 вражеских бронзовых отрядов в противоположном ряду, заменив их силу на 1 ед.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
            {
                id: 'nilfgaard_artifact_2',
                name: 'Руна Даждьбог',
                type: 'artifact',
                faction: 'nilfgaard',
                image: 'dazhdbog.mp4',
                description: 'Артефакт',
				descriptionfull: 'Сыграйте бронзовую карту Нильфгаарда',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
            {
                id: 'nilfgaard_artifact_3',
                name: 'Рабский ошейник',
                type: 'artifact',
                faction: 'nilfgaard',
                image: 'rab.mp4',
                description: 'Артефакт',
				descriptionfull: 'Заблокируйте вражеский отряд и нанесите ему 3 ед. урона',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/nilfgaard/banner_bronze.png'
            },
		]
    },

    realms: {
        units: [
            {
                id: 'realms_unit_1',
                name: 'Фольтест',
				namefull: 'Фольтест',
                strength: 10,
                type: 'unit',
                faction: 'realms',
                image: 'foltest.mp4',
                description: 'Король Темерии',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'gold',
                tags: ['leader', 'king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/realms/banner_gold.png'
            },
            {
                id: 'realms_unit_2',
                name: 'Радовид V',
				namefull: 'Радовид V',
                strength: 9,
                type: 'unit',
                faction: 'realms',
                image: 'radovid.mp4',
                description: 'Король Редании',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/realms/banner_gold.png'
            },
            {
                id: 'realms_unit_3',
                name: 'Хенсельт',
				namefull: 'Хенсельт',
                strength: 9,
                type: 'unit',
                faction: 'realms',
                image: 'henselt.mp4',
                description: 'Король Каэдвена',
				descriptionfull: '---',
				ability: '---',
                position: 'any-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/realms/banner_gold.png'
            },
            {
                id: 'realms_unit_4',
                name: 'Стеннис',
				namefull: 'Стеннис',
                strength: 5,
                type: 'unit',
                faction: 'realms',
                image: 'stennis.mp4',
                description: 'Принц Аэдирна',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'bronze',
                tags: ['king'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_unit_5',
                name: 'Роше',
				namefull: 'Вернон Роше',
                strength: 7,
                type: 'unit',
                faction: 'realms',
                image: 'roche.mp4',
                description: 'Безжалостный убийца',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'bronze',
                tags: ['soldier'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_unit_6',
                name: 'Адда',
				namefull: 'Принцесса Адда',
                strength: 6,
                type: 'unit',
                faction: 'realms',
                image: 'adda.mp4',
                description: 'Проклятая принцесса Тимерии',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/realms/banner_position.png',
                rarity: 'bronze',
                tags: ['kingser'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
        ],
        specials: [
            {
                id: 'realms_special_1',
                name: 'Руническое слово',
                type: 'special',
                faction: 'realms',
                image: 'runes.mp4',
                description: 'Заклинание',
				descriptionfull: 'Сотворите и сыграйте бронзового чародея Королевств Севера и добавьте ему щит',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['spell'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
		],
        tactics: [
            {
                id: 'realms_tactic_1',
                name: 'Подкрипление',
                type: 'tactic',
                faction: 'realms',
                image: 'tactic.mp4',
                description: 'Тактика',
				descriptionfull: '----',
				ability: 'morale_boost',
                rarity: 'bronze',
                tags: ['tactic'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
		],
        artifacts: [
            {
                id: 'realms_artifact_1',
                name: 'Меч Вандергрифта',
                type: 'artifact',
                faction: 'realms',
                image: 'sword.mp4',
                description: 'Артефакт',
				descriptionfull: 'Нанесите 5 ед. урона вражескому отряду',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_artifact_2',
                name: 'Руна Зоря',
                type: 'artifact',
                faction: 'realms',
                image: 'zorya.mp4',
                description: 'Артефакт',
				descriptionfull: 'Сыграйте бронзовую карту Королевств Севера',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
            {
                id: 'realms_artifact_3',
                name: 'Кровавый бич',
                type: 'artifact',
                faction: 'realms',
                image: 'blood.mp4',
                description: 'Артефакт',
				descriptionfull: 'Добавьте кровотечение вражескому отряду на 8 ходов',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/realms/banner_bronze.png'
            },
		]
    },

    scoiatael: {
        units: [
            {
                id: 'scoiatael_unit_1',
                name: 'Францеска',
				namefull: 'Францеска Финдабаир',
                strength: 10,
                type: 'unit',
                faction: 'scoiatael',
                image: 'francesca.mp4',
                description: 'Княгиня Дол Блатанны',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['mage', 'leader'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
            {
                id: 'scoiatael_unit_2',
                name: 'Филавандрель',
				namefull: 'Филавандрель',
                strength: 9,
                type: 'unit',
                faction: 'scoiatael',
                image: 'filavandrel.mp4',
                description: 'Предводитель эльфов Синих гор',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
            {
                id: 'scoiatael_unit_3',
                name: 'Брувер',
				namefull: 'Брувер Гоог',
                strength: 9,
                type: 'unit',
                faction: 'scoiatael',
                image: 'goog.mp4',
                description: 'Староста Махакама',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
            {
                id: 'scoiatael_unit_4',
                name: 'Эитнэ',
				namefull: 'Эитнэ',
                strength: 9,
                type: 'unit',
                faction: 'scoiatael',
                image: 'eitne.mp4',
                description: 'Правительница Брокилона',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
			{
                id: 'scoiatael_unit_6',
                name: 'Эльфская разведчица',
				namefull: 'Эльфская разведчица',
                strength: 4,
                type: 'unit',
                faction: 'scoiatael',
                image: 'scout.mp4',
                description: 'Эльфийка',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['soldier'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
			{
                id: 'scoiatael_unit_7',
                name: 'Эльдайн',
				namefull: 'Эльдайн',
                strength: 8,
                type: 'unit',
                faction: 'scoiatael',
                image: 'eldains.mp4',
                description: 'Эльф',
				descriptionfull: 'Лидер и командир отряда Скоя\'таэлей',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/scoiatael/banner_position.png',
                rarity: 'gold',
                tags: ['soldier'],
                border: 'deck/bord_gold.png',
                banner: 'faction/scoiatael/banner_gold.png'
            },
        ],
        specials: [
            {
                id: 'scoiatael_special_1',
                name: 'Круг жизни',
                type: 'special',
                faction: 'scoiatael',
                image: 'life.mp4',
                description: 'Природа',
				descriptionfull: 'Нанесите 3 ед. урона вражескому отряду, затем усильте случайный не нейтральный отряд в вашей руке на 2 ед.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['spell'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
            {
                id: 'scoiatael_special_2',
                name: 'Зов леса',
                type: 'special',
                faction: 'scoiatael',
                image: 'voise.mp4',
                description: 'Природа',
				descriptionfull: 'Сыграйте не нейтральный отряд из вашей колоды и усильте его на 1 ед.',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['spell'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
		],
        tactics: [],
        artifacts: [
            {
                id: 'scoiatael_artifact_1',
                name: 'Махакамский рог',
                type: 'artifact',
                faction: 'scoiatael',
                image: 'rog.mp4',
                description: 'Артефакт',
				descriptionfull: 'Усильте смежные отряды на 3 ед.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
            {
                id: 'scoiatael_artifact_2',
                name: 'Руна Марена',
                type: 'artifact',
                faction: 'scoiatael',
                image: 'marena.mp4',
                description: 'Артефакт',
				descriptionfull: 'Сыграйте бронзовую карту Скоя\'таэлей',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
            {
                id: 'scoiatael_artifact_3',
                name: 'Шар видения',
                type: 'artifact',
                faction: 'scoiatael',
                image: 'vision.mp4',
                description: 'Артефакт',
				descriptionfull: 'Усильте дружественный отряд на 2 ед.',
				ability: 'torrential_rain',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/scoiatael/banner_bronze.png'
            },
		]
    },

    skellige: {
        units: [
            {
                id: 'skellige_unit_1',
                name: 'Бран',
				namefull: 'Бран Тиршах',
                strength: 10,
                type: 'unit',
                faction: 'skellige',
                image: 'bran.mp4',
                description: 'Король Скеллиге',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['leader', 'king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
            {
                id: 'skellige_unit_2',
                name: 'Эйст',
				namefull: 'Эйст Тиршах',
                strength: 9,
                type: 'unit',
                faction: 'skellige',
                image: 'eist.mp4',
                description: 'Ярл клана Тиршах',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
            {
                id: 'skellige_unit_3',
                name: 'Крах',
				namefull: 'Крах ан Крайт',
                strength: 9,
                type: 'unit',
                faction: 'skellige',
                image: 'krah.mp4',
                description: 'Ярл клана ан Крайт',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
            {
                id: 'skellige_unit_4',
                name: 'Харальд Хромой',
				namefull: 'Харальд Хромой',
                strength: 9,
                type: 'unit',
                faction: 'skellige',
                image: 'harald.mp4',
                description: 'Древний король Скеллиге',
				descriptionfull: '---',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['king'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
			{
                id: 'skellige_unit_5',
                name: 'Фламиника',
				namefull: 'Фламиника',
                strength: 5,
                type: 'unit',
                faction: 'skellige',
                image: 'flaminica.mp4',
                description: 'Друин клана Хэймэй',
				descriptionfull: 'Фламиника — предводительница круга друидов',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['soldier', 'mage'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
			{
                id: 'skellige_unit_6',
                name: 'Керис',
				namefull: 'Керис ан Крайт',
                strength: 6,
                type: 'unit',
                faction: 'skellige',
                image: 'cerys.mp4',
                description: 'Неустрашимая',
				descriptionfull: 'Дочь ярла Краха ан Крайта',
				ability: '---',
                position: 'close-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['kingser'],
                border: 'deck/bord_gold.png',
                banner: 'faction/skellige/banner_gold.png'
            },
			{
                id: 'skellige_unit_7',
                name: 'Хольгер',
				namefull: 'Хольгер Чернорукий',
                strength: 6,
                type: 'unit',
                faction: 'skellige',
                image: 'blackhand.mp4',
                description: 'Лидером клана Димун',
				descriptionfull: 'Бывший ярл Фарерских островов.',
				ability: '---',
                position: 'ranged-row',
                positionBanner: 'faction/skellige/banner_position.png',
                rarity: 'gold',
                tags: ['kingser'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
        ],
        specials: [
            {
                id: 'skellige_special_1',
                name: 'Шторм Скеллиге',
                type: 'special',
                faction: 'skellige',
                image: 'storm.mp4',
                description: 'Природа',
				descriptionfull: 'Создайте эффект шторма в ряду противника на 2 хода',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['weather'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
		],
        tactics: [],
        artifacts: [
            {
                id: 'skellige_artifact_1',
                name: 'Магический компас',
                type: 'artifact',
                faction: 'skellige',
                image: 'compas.mp4',
                description: 'Артефакт',
				descriptionfull: 'Выберите одну из 3 верхних карт в вашей колоде, сыграйте ее и переместите остальные в ваш сброс',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
            {
                id: 'skellige_artifact_2',
                name: 'Руна Стрибог',
                type: 'artifact',
                faction: 'skellige',
                image: 'stribog.mp4',
                description: 'Артефакт',
				descriptionfull: 'Сыграйте бронзовую карту Скеллиге',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
            {
                id: 'skellige_artifact_3',
                name: 'Слезы сирены',
                type: 'artifact',
                faction: 'skellige',
                image: 'sirena.mp4',
                description: 'Артефакт',
				descriptionfull: 'Создайте эффект дождя в ряду противника на 2 хода',
				ability: 'storm',
                rarity: 'bronze',
                tags: ['artifact'],
                border: 'deck/bord_bronze.png',
                banner: 'faction/skellige/banner_bronze.png'
            },
		]
    },
};

function normalizeCardPositions(cards) {
    return cards.map(card => {
        if (card.position && Array.isArray(card.position) && card.position.length > 1) {
            return {
                ...card,
                position: ['any-row']
            };
        }
        return card;
    });
}

Object.keys(cardsData).forEach(faction => {
    Object.keys(cardsData[faction]).forEach(type => {
        if (Array.isArray(cardsData[faction][type])) {
            cardsData[faction][type] = normalizeCardPositions(cardsData[faction][type]);
        }
    });
});

function getFactionCards(factionId) {
    const factionCards = {
        units: [...cardsData[factionId].units],
        specials: [...cardsData[factionId].specials],
        artifacts: [...cardsData[factionId].artifacts],
        tactics: [...cardsData[factionId].tactics] 
    };

    factionCards.units.push(...cardsData.neutral.units);
    factionCards.specials.push(...cardsData.neutral.specials);
    factionCards.artifacts.push(...cardsData.neutral.artifacts);
    factionCards.tactics.push(...cardsData.neutral.tactics || []);

    return factionCards;
}

function getCardById(cardId) {
    for (const faction in cardsData) {
        for (const type in cardsData[faction]) {
            const card = cardsData[faction][type].find(c => c.id === cardId);
            if (card) return card;
        }
    }
    return null;
}

function getCardsByTag(tag) {
    const result = {
        units: [],
        specials: [],
        artifacts: []
    };

    for (const faction in cardsData) {
        for (const type in cardsData[faction]) {
            cardsData[faction][type].forEach(card => {
                if (card.tags && card.tags.includes(tag)) {
                    result[type].push(card);
                }
            });
        }
    }

    return result;
}

function getAllCards() {
    return cardsData;
}

window.cardsModule = {
    getFactionCards,
    getCardById,
    getCardsByTag,
    getAllCards,
    cardsData
};